# Generated by Django 2.2.2 on 2020-01-23 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200123_1626'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
