# Generated by Django 3.0.2 on 2020-01-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200127_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
