# Generated by Django 3.0.2 on 2020-02-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20200203_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('D', 'Devices'), ('O', 'Others'), ('A', 'Accessory')], default='D', max_length=1),
            preserve_default=False,
        ),
    ]
