# Generated by Django 3.0.2 on 2020-02-12 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
