# Generated by Django 3.0.2 on 2020-02-12 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_remove_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='ordered',
        ),
    ]
