# Generated by Django 3.0.2 on 2020-02-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_remove_orderproduct_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
