# Generated by Django 3.0.2 on 2020-02-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20200212_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trailer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
