# Generated by Django 3.0.2 on 2020-02-11 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20200210_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='user',
        ),
    ]
