# Generated by Django 3.0.2 on 2020-03-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_product_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_img',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
