# Generated by Django 3.0.2 on 2020-02-11 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_orderproduct_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_date',
        ),
    ]
