# Generated by Django 2.2.2 on 2019-07-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190710_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('summary', models.TextField(help_text='Введите краткое описание ', max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Guns',
        ),
    ]
