# Generated by Django 2.2.2 on 2019-07-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190723_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
