# Generated by Django 2.2.2 on 2019-07-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190725_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rifle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rif_name', models.CharField(blank=True, max_length=100)),
                ('rif_summary', models.TextField(blank=True, max_length=4000)),
                ('rname', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
