# Generated by Django 2.2.2 on 2019-07-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_rifle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rifle',
            name='rif_name',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
