# Generated by Django 2.2.2 on 2019-08-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_bookinstance_rifle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_g', models.TextField(blank=True, max_length=4000)),
                ('gname', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='rifle',
            name='rif_summary',
            field=models.TextField(blank=True, max_length=6000),
        ),
    ]
