# Generated by Django 2.2.2 on 2019-08-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20190806_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='img_g',
            field=models.TextField(blank=True, max_length=6000),
        ),
    ]
